(define-skeleton header-skeleton
  "Define a C++ header file skeleton"
  ""
  "// Copyright Dassault Systemes Simulia Corp.\n\n"
  "#pragma once\n\n"
  "#include \"base/WinExportDefs.h\"\n\n"
  "namespace " (skeleton-read "Namespace name?") "\n"
  "{\n\n"
  "class SPCK_XXX_EXPORT " (file-name-sans-extension (file-name-nondirectory buffer-file-name)) "\n"
  "{\n"
  "public:\n\n"
  "   " (file-name-sans-extension (file-name-nondirectory buffer-file-name)) "(const " (file-name-sans-extension (file-name-nondirectory buffer-file-name)) "&) = delete;\n"
  "   " (file-name-sans-extension (file-name-nondirectory buffer-file-name)) "& operator=(const " (file-name-sans-extension (file-name-nondirectory buffer-file-name)) "&) = delete;\n"
  "};\n"
  "}\n"
)
