(define-skeleton header-skeleton
  "Define a C++ header file skeleton"
  ""
"#ifndef __" (upcase (file-name-sans-extension (file-name-nondirectory buffer-file-name))) "_H__\n"
"#define __" (upcase (file-name-sans-extension (file-name-nondirectory buffer-file-name))) "_H__\n\n"
"// Copyright Dassault Systemes Simulia Corp.\n\n"
"#include \"base/WinExportDefs.h\"\n\n"
"namespace " (skeleton-read "Namespace name?") "\n"
"{\n\n"
"class SPCK_XXX_EXPORT " (file-name-sans-extension (file-name-nondirectory buffer-file-name)) "\n"
"{\n"
"public:\n\n"
"   " (file-name-sans-extension (file-name-nondirectory buffer-file-name)) "(const " (file-name-sans-extension (file-name-nondirectory buffer-file-name)) "&) = delete;\n"
"   " (file-name-sans-extension (file-name-nondirectory buffer-file-name)) "& operator=(const " (file-name-sans-extension (file-name-nondirectory buffer-file-name)) "&) = delete;\n"
"};\n"
"}\n"
"#endif // __" (upcase (file-name-sans-extension (file-name-nondirectory buffer-file-name))) "_H__\n"
)
